/* ============================================================
   Datos para el panel de sugerencias — AISAB
   Zonas confirmadas por Mario (06/06/2026).
   Calles: callejero público de San Antonio de Benagéber
   (callejero.net), nombres normalizados y sin duplicados.
   PENDIENTE: validar lista con Mario y agrupar por zona.
   ============================================================ */

const ZONAS = [
  "Casco urbano",
  "Montesano",
  "Colinas de San Antonio",
  "Cumbres de San Antonio",
  "San Vicente",
  "Benagolf",
  "Otra / no lo sé"
];

const AREAS = [
  "Atención al Ciudadano",
  "Bienestar Animal",
  "Bienestar Social",
  "Comercio y Desarrollo Local",
  "Cultura y Fiestas",
  "Deportes",
  "Educación",
  "Hacienda",
  "Igualdad",
  "Juventud",
  "Medio Ambiente",
  "Movilidad",
  "Nuevas Tecnologías",
  "Parques y Jardines",
  "Políticas Inclusivas",
  "Sanidad",
  "Seguridad Ciudadana",
  "Servicios",
  "Urbanismo y Obras",
  "Otra"
];

const CALLES = [
  "Avenida 8 de Abril",
  "Avenida Cortes de Medio",
  "Avenida de Benagéber",
  "Avenida de la Pobla de Vallbona",
  "Avenida Doctor Severo Ochoa",
  "Avenida San Antonio de Benagéber",
  "Calle Abellerol",
  "Calle Abetos",
  "Calle Águila",
  "Calle Albers",
  "Calle Alcarava",
  "Calle Algar",
  "Calle Armelers",
  "Calle Arrieta",
  "Calle Barchel",
  "Calle Bequeruda",
  "Calle Bidasoa",
  "Calle Búho",
  "Calle Cabriol",
  "Calle Cadernera",
  "Calle Calandria",
  "Calle Camallonga",
  "Calle Camelias",
  "Calle Canari",
  "Calle Canyoles",
  "Calle Capsot",
  "Calle Casas del Medio",
  "Calle Cervantes",
  "Calle Cervera",
  "Calle Cérvol",
  "Calle Charco Negro",
  "Calle Cisne",
  "Calle Clariano",
  "Calle Claveles",
  "Calle Cluixidell",
  "Calle Coll Vert",
  "Calle Colom",
  "Calle Corp",
  "Calle Corriolet",
  "Calle Cucut",
  "Calle Daltá",
  "Calle de la Llevant",
  "Calle de la Masía de San Antonio",
  "Calle de la Muela",
  "Calle de la Oca",
  "Calle de la Ollería",
  "Calle de la Purísima",
  "Calle de las Moreras",
  "Calle de los Cipreses",
  "Calle de los Gladiolos",
  "Calle de los Jacintos",
  "Calle de los Limoneros",
  "Calle de los Manzanos",
  "Calle de los Olmos",
  "Calle de los Xiprers",
  "Calle del Pou",
  "Calle del Topacio",
  "Calle Doctor Marañón",
  "Calle Esparver",
  "Calle Esplugabous",
  "Calle Estornell",
  "Calle Falcia",
  "Calle Falcó",
  "Calle Flamenc",
  "Calle Formiguer",
  "Calle Fotja",
  "Calle Fuente de la Cortina",
  "Calle Fuente de la Ocecilla",
  "Calle Fuente del Rodenillo",
  "Calle Fumarell",
  "Calle Fusell",
  "Calle Gafarda",
  "Calle Gafarro",
  "Calle Garbí",
  "Calle Garza",
  "Calle Gavina",
  "Calle Gregal",
  "Calle Grilluelos",
  "Calle Griva",
  "Calle Guadalaviar",
  "Calle Guatla",
  "Calle Lavanda",
  "Calle Llebeig",
  "Calle Llimeres",
  "Calle Llorers",
  "Calle Magnolia",
  "Calle Magre",
  "Calle Malvasía",
  "Calle Martinet",
  "Calle Mascarell",
  "Calle Mata Parda",
  "Calle Mayor",
  "Calle Merla",
  "Calle Mestral",
  "Calle Migjorn",
  "Calle Milà",
  "Calle Millars",
  "Calle Mimosas",
  "Calle Montnegre",
  "Calle Mussol",
  "Calle Nieva",
  "Calle Olocastre",
  "Calle Palancia",
  "Calle Palomas",
  "Calle Pasarell",
  "Calle Pelicà",
  "Calle Peña del Mediodía",
  "Calle Pensamiento",
  "Calle Perdiu",
  "Calle Perigall",
  "Calle Picachos",
  "Calle Piedras Picadas",
  "Calle Pinsà",
  "Calle Pinyoner",
  "Calle Pitroig",
  "Calle Piuleta",
  "Calle Piulo",
  "Calle Pomeres",
  "Calle Ponent",
  "Calle Puput",
  "Calle Rasclò",
  "Calle Rincón del Molino",
  "Calle Río Deva",
  "Calle Río Duero",
  "Calle Rosseta",
  "Calle Saboc",
  "Calle Sabina",
  "Calle San Vicente Ferrer",
  "Calle Sarset",
  "Calle Segura",
  "Calle Senia",
  "Calle Serpis",
  "Calle Sit",
  "Calle Tangarinos",
  "Calle Terrerola",
  "Calle Titet",
  "Calle Tort",
  "Calle Tórtola",
  "Calle Tortosa",
  "Calle Tramuntana",
  "Calle Tulipanes",
  "Calle Turcas",
  "Calle Turia",
  "Calle Verderol",
  "Calle Vereda",
  "Calle Villanueva",
  "Calle Vinalopó",
  "Calle Xaloc",
  "Calle Xorlito",
  "Calle Xudia",
  "Calle Xúquer",
  "Callejón de Vereda",
  "Camino de Bétera",
  "Camino de Mas Camarena",
  "Camino de San Antonio a Bétera",
  "Paseo de Valencia",
  "Plaza de la Colonización",
  "Plaza de la Concordia",
  "Plaza de la Diputación",
  "Plaza del Ayuntamiento",
  "Vereda Real"
];
